{
 "title": "Reply main board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "System Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$application\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "Total requests (min)"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 3, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=\"$application\"}[1m])*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(system_cpu_usage{job=\"$application\"}[1m])*100"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "New users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=\"200\", route=\"/auth/admin/signup\", method=\"POST\", job=\"$application\"}[1m]))",
     "legendFormat": "New users"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",route!=\"/api/metrics/..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^4..$\", status!=\"^401$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",route!=\"/api/metrics/..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^401$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",route!=\"/api/metrics/..$\"}[1m]))",
     "legendFormat": "Unauthorised Errors Rate"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ktor_http_server_requests_seconds{route!=\"/api/open/metrics\",route!=\"/api/open/health\",route!=\"/api/metrics/..$\",job=\"$application\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Response time of 95% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{job=\"$application\", route!=\"/api/open/metrics\",route!=\"/api/open/health\", quantile=\"0.95\"}[1m])",
     "legendFormat": "{{route}} 95%"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum by(route, method) (ktor_http_server_requests_seconds_count{route!=\"/api/open/metrics\", route!=\"/api/open/health\", route!=\"/api/metrics/{service}\", route!=\"/api/metrics/user\", job=\"$application\"})",
     "legendFormat": "{{method}}  {{route}}"
    }
   ]
  },
  {
   "title": "Response time of 90% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{job=\"$application\", route!=\"/api/open/metrics\",route!=\"/api/open/health\", quantile=\"0.9\"}[1m])",
     "legendFormat": "{{route}} 95%"
    }
   ]
  },
  {
   "title": "Errors by API",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{route!=\"/api/open/metrics\",route!=\"/api/open/health\", status!=\"200\",job=\"$application\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=\"^4..$\", status!=\"^401$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\",job=\"$application\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^401$\", route!=\"/api/open/metrics\",route!=\"/api/open/health\"}[1m]))",
     "legendFormat": "Unauthorised Errors Rate"
    }
   ]
  },
  {
   "title": "Response time of 50% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{job=\"$application\", route!=\"/api/open/metrics\",route!=\"/api/open/health\", quantile=\"0.5\"}[1m])",
     "legendFormat": "{{route}} 50%"
    }
   ]
  }
 ]
}