scrape_configs:
  - job_name: 'UserService'
    metrics_path: /api/open/metrics
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - UserService.json
  - job_name: 'TestService'
    metrics_path: /api/open/metrics
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - TestService.json
  - job_name: 'FileService'
    metrics_path: /api/open/metrics
    scrape_interval: 5s
    file_sd_configs:
      - files:
          - FileService.json
  - job_name: 'Gateway'
    metrics_path: /api/open/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal']